config/routes.rb
Rails.application.routes.draw do
  root to: 'staff/homes#start'

  namespace :admin do
    get 'graphs/:id' => "members#graph"
    get 'search' => 'search'
    resources :members, only: [:index, :show, :edit, :update]
  end
  scope module: :staff do
    get 'graphs' => 'conditions#graph'
    resources :conditions, only: [:new, :create, :show, :destroy, :index]
  end
  devise_for :members, skip: [:passwards], controllers: {
    registrations: "staff/registrations",
    sessions: 'staff/sessions',
  }

  devise_for :admins, skip: [:passwards, :registrations], controllers: {
    sessions: "admin/sessions",
  }

  scope module: :staff do
    get 'my_page' => 'members#top'
    patch 'change' => 'members#change'
    get "search" => "search"
    resources :members, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    get 'top' => 'homes#top'
  end

  namespace :admin do
    resources :sections, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
  has_many :condition

  def self.search(search)
    search ? where(["first_name like? OR last_name like?", "%#{search}%", "%#{search}"]) : all
  end

  enum attendance_status: { leaving_work: 0, attendance: 1 }

  validates :first_name, { presence: true }
  validates :last_name, { presence: true }
  validates :first_name_kana, { presence: true }
  validates :last_name_kana, { presence: true }
  validates :birth_year, { presence: true }
  validates :birth_month, { presence: true }
  validates :birth_day, { presence: true }
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    type = params[:type] || Section.ids
    @member = Member.where(section_id: type).search(params[:search])
    @sections = Section.all
  end

  def show
    @member = Member.find(params[:id])
    @condition = @member.condition.limit(1).order(created_at: :desc)
  end

  def graph
    @member = Member.find(params[:id])
    @conditions = @member.condition
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to admin_member_path(@member.id)
  end

  private

  def member_params
    params.require(:member).permit(:section_id)
  end
end

app/controllers/staff/members_controller.rb
class Staff::MembersController < ApplicationController
  before_action :authenticate_member!

  def top
    @member = current_member
    @condition = @member.condition.limit(1).order(created_at: :desc)
  end

  def change
    @member = Member.find(current_member.id)
    @member.update(update_params)
    redirect_to my_page_path
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member = Member.find(current_member.id)
    if @member.update(member_params)
      redirect_to my_page_path
    else
      render :edit
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def index
    # if params[:type] == '1'
    #   @member = Member.where(section_id: 1)
    # elsif params[:type] == '2'
    #   @member = Member.where(section_id: 2)
    # else
    #   @member = Member.all.search(params[:search])
    # end
    type = params[:type] || Section.ids
    @member = Member.where(section_id: type).search(params[:search])
    @sections = Section.all
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :birth_year, :birth_month, :birth_day, :phone_number, :address, :email, :section_id, :attendance_status)
  end

  def update_params
    params.require(:member).permit(:attendance_status)
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/staff/members_helper.rb
module Staff::MembersHelper
end

app/views/admin/members/_section_list.html.erb
 <h2 class="mt-2 mb-3">部門</h2>
 <div>
   <% section.each do |section| %>
   <ul class="list-group list-group-flish">
       <li class="list-group-item">
        <%= link_to admin_members_path({type: section.id}) do %>
          <%= section.section_name %>
        <% end %>
        </li>
   </ul>
   <% end %>
 </div>

app/views/admin/members/edit.html.erb
<div class="container">
  <div clas=" row justify-content-center">
    <div class="col-8">
      <h1 class="mt-4 mb-4">所属部門変更</h1>
      <div class="row justify-content-center">
        <%= form_with model: @member, url: admin_member_path(@member.id), method: :patch do |f| %>
          <div class="form-group">
            <%= f.select :section_id, options_from_collection_for_select(Section.all, :id, :section_name) %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/graph.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1 class="mt-3 mb-4">体温変遷グラフ</h1>
      <div>
        <%= line_chart @conditions.pluck(:created_at, :temperature).map{|item| [item[0].to_date, item[1]]}, min: 35, max: 38 %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1 class="mt-3 mb-4">所属社員一覧</h1>
      <div class="row">
        <div class="col-md-2">
          <%= render 'admin/members/section_list', section: @sections %>
        </div>
        <div class= "col-md-9">
          <div class="mb-4 text-center">
            <%= form_tag(admin_members_path, method: :get) do %>
              <%= text_field_tag :search %>
              <%= submit_tag 'search', name: nil, class: "btn btn-success ml-2" %>
            <% end %>
          </div>
          <div>
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th>社員ID</th>
                  <th>社員名</th>
                  <th>所属課</th>
                </tr>
             </thead>
             <tbody>
                <% @member.each do |member| %>
                <tr>
                  <td><%= member.id %></td>
                  <td>
                    <%= link_to admin_member_path(member.id) do %>
                      <%= member.first_name %><%= member.last_name %>
                    <% end %>
                  </td>
                  <td><%= member.section.section_name %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        
    </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1 class="mt-3 mb-4"><%= @member.first_name %><%= @member.last_name %>さんの詳細</h1>
        <div class="row justify-content-end">
          <%= link_to "所属部門を変更する", edit_admin_member_path(@member.id), class: "btn btn-primary" %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・社員ID</h5>
          <%= @member.id %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・社員名</h5>
           <%= @member.first_name %> <%= @member.last_name %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・社員名（フリガナ）</h5>
          <%= @member.first_name_kana %> <%= @member.last_name_kana %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・生年月日</h5>
          <%= @member.birth_year %>年 <%= @member.birth_month %>月 <%= @member.birth_day %>日
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・電話番号</h5>
          <%= @member.phone_number %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・住所</h5>
          <%= @member.address %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・所属部門</h5>
          <%= @member.section.section_name %>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-3">・出退勤状況</h5>
          <%= @member.attendance_status_i18n %>
        </div>
        <div class="field">
          <h5 class="mb-3">・最近の体調</h5>
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>登録日時</th>
                <th>体調</th>
                <th>体温</th>
                <th>補足説明</th>
              </tr>
            </thead>
            <tbody>
              <% @condition.each do |condition| %>
              <tr>
                <td><%= condition.created_at.to_s(:datetime_jp) %></td>
                <td><%= condition.status_i18n %></td>
                <td><%= condition.temperature %></td>
                <td><%= condition.explation %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="row justify-content-end">
          <%= link_to "体温変遷グラフ画面へ", admin_path(@member.id), class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>