config/routes.rb
Rails.application.routes.draw do
  root to: 'staff/homes#start'

  namespace :admin do
    get 'graphs/:id' => "members#graph"
    get 'search' => 'search'
    resources :members, only: [:index, :show, :edit, :update]
  end
  scope module: :staff do
    get 'graphs' => 'conditions#graph'
    resources :conditions, only: [:new, :create, :show, :destroy, :index]
  end
  devise_for :members, skip: [:passwards], controllers: {
    registrations: "staff/registrations",
    sessions: 'staff/sessions',
  }

  devise_for :admins, skip: [:passwards, :registrations], controllers: {
    sessions: "admin/sessions",
  }

  scope module: :staff do
    get 'my_page' => 'members#top'
    patch 'change' => 'members#change'
    get "search" => "search"
    resources :members, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    get 'top' => 'homes#top'
  end

  namespace :admin do
    resources :sections, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :member

  validates :section_name, { presence: true, uniqueness: true }
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @sections = Section.all
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to admin_sections_path
    else
      @sections = Section.all
      render :index
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to admin_sections_path
    else
      render :edit
    end
  end

  private

  def section_params
    params.require(:section).permit(:section_name)
  end
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/views/admin/sections/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h2 class="mt-3 mb-4">部門編集</h2>
      <% if @section.errors.any? %>
        <%= @section.errors.count %>件のエラーが発生しました
        <ul>
          <% @section.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="row justify-content-center">
        <%= form_with model: @section, url: admin_section_path(@section.id), method: :patch do |f| %>
          <div class="form-group">
            <%= f.text_field :section_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: "btn btn-success btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/sections/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h2 class="mt-3 mb-4">部門登録</h2>
      <% if @section.errors.any? %>
        <h4><%= @section.errors.count %>件のエラーが発生しました</h4>
        <ul>
          <% @section.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @section, url: admin_sections_path, method: :post  do |f| %>
        <div class="row justify-content-center">
          <div class="col-3">
            <%= f.text_field :section_name, class: "form-control", placeholder: "部門名" %>
          </div>
          <div class="col-3">
            <%= f.submit "保存する", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
      <div class="row mt-4">
        <h2 class="mt-2 mb-3">部門一覧</h2>
        <table class="table text-center">
          <tbody>
            <% @sections.each do |section| %>
            <tr>
              <td><%= section.section_name %></td>
              <td><%= link_to "編集する", edit_admin_section_path(section.id), class: "btn btn-primary" %></td>
            </tr>
            <% end %>
          </tbody>
       </table>
      </div>
    </div>
  </div>
</div>