config/routes.rb
Rails.application.routes.draw do
  root to: 'staff/homes#start'

  namespace :admin do
    get 'graphs/:id' => "members#graph"
    get 'search' => 'search'
    resources :members, only: [:index, :show, :edit, :update]
  end
  scope module: :staff do
    get 'graphs' => 'conditions#graph'
    resources :conditions, only: [:new, :create, :show, :destroy, :index]
  end
  devise_for :members, skip: [:passwards], controllers: {
    registrations: "staff/registrations",
    sessions: 'staff/sessions',
  }

  devise_for :admins, skip: [:passwards, :registrations], controllers: {
    sessions: "admin/sessions",
  }

  scope module: :staff do
    get 'my_page' => 'members#top'
    patch 'change' => 'members#change'
    get "search" => "search"
    resources :members, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    get 'top' => 'homes#top'
  end

  namespace :admin do
    resources :sections, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
  has_many :condition

  def self.search(search)
    search ? where(["first_name like? OR last_name like?", "%#{search}%", "%#{search}"]) : all
  end

  enum attendance_status: { leaving_work: 0, attendance: 1 }

  validates :first_name, { presence: true }
  validates :last_name, { presence: true }
  validates :first_name_kana, { presence: true }
  validates :last_name_kana, { presence: true }
  validates :birth_year, { presence: true }
  validates :birth_month, { presence: true }
  validates :birth_day, { presence: true }
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    type = params[:type] || Section.ids
    @member = Member.where(section_id: type).search(params[:search])
    @sections = Section.all
  end

  def show
    @member = Member.find(params[:id])
    @condition = @member.condition.limit(1).order(created_at: :desc)
  end

  def graph
    @member = Member.find(params[:id])
    @conditions = @member.condition
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to admin_member_path(@member.id)
  end

  private

  def member_params
    params.require(:member).permit(:section_id)
  end
end

app/controllers/staff/conditions_controller.rb
class Staff::ConditionsController < ApplicationController
  before_action :authenticate_member!

  def new
    @condition = Condition.new
  end

  def create
    @condition = Condition.new(condition_params)
    @condition.member_id = current_member.id
    # pp @condition, current_member,"test", "hoge"
    if @condition.save
      redirect_to condition_path(@condition.id)
    else
      render :new
    end
  end

  def show
    @condition = Condition.find(params[:id])
  end

  def destroy
    @condition = Condition.find(params[:id])
    @condition.member.id = current_member.id
    @condition.destroy
    redirect_to conditions_path
  end

  def index
    @conditions = current_member.condition
    pp @conditions
  end

  def graph
    @conditions = current_member.condition
  end

  private

  def condition_params
    params.require(:condition).permit(:member_id, :temperature, :status, :explation)
  end
end

app/controllers/staff/confirmations_controller.rb
# frozen_string_literal: true

class Staff::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staff/homes_controller.rb
class Staff::HomesController < ApplicationController
  def start
  end
end

app/controllers/staff/members_controller.rb
class Staff::MembersController < ApplicationController
  before_action :authenticate_member!

  def top
    @member = current_member
    @condition = @member.condition.limit(1).order(created_at: :desc)
  end

  def change
    @member = Member.find(current_member.id)
    @member.update(update_params)
    redirect_to my_page_path
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member = Member.find(current_member.id)
    if @member.update(member_params)
      redirect_to my_page_path
    else
      render :edit
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def index
    # if params[:type] == '1'
    #   @member = Member.where(section_id: 1)
    # elsif params[:type] == '2'
    #   @member = Member.where(section_id: 2)
    # else
    #   @member = Member.all.search(params[:search])
    # end
    type = params[:type] || Section.ids
    @member = Member.where(section_id: type).search(params[:search])
    @sections = Section.all
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :birth_year, :birth_month, :birth_day, :phone_number, :address, :email, :section_id, :attendance_status)
  end

  def update_params
    params.require(:member).permit(:attendance_status)
  end
end

app/controllers/staff/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staff::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staff/passwords_controller.rb
# frozen_string_literal: true

class Staff::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staff/registrations_controller.rb
# frozen_string_literal: true

class Staff::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_sign_in_path_for(resource)
    my_page_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staff/sessions_controller.rb
# frozen_string_literal: true

class Staff::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    my_page_path
  end

  def after_sign_out_path_for(resource)
    new_member_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/staff/unlocks_controller.rb
# frozen_string_literal: true

class Staff::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/staff/conditions_helper.rb
module Staff::ConditionsHelper
end

app/helpers/staff/homes_helper.rb
module Staff::HomesHelper
end

app/helpers/staff/members_helper.rb
module Staff::MembersHelper
end

app/views/staff/members/_section_list.html.erb
 <h2 class="mt-2 mb-3">部門</h2>
 <div>
   <% section.each do |section| %>
   <ul class="list-group list-group-flish">
       <li class="list-group-item">
        <%= link_to members_path({type: section.id}) do %>
          <%= section.section_name %>
        <% end %>
        </li>
   </ul>
   <% end %>
 </div>

app/views/staff/members/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1 class="mt-3 mb-4">登録情報編集</h1>
      <div>
        <% if @member.errors.any? %>
          <h4><%= @member.errors.count %>件のエラーが発生しました</h4>
          <ul>
            <% @member.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @member, url: member_path(@member.id), method: :patch do |f| %>
          <div class="row">
            <h5>・社員氏名</h5>
            <div class="form-group col-md-3">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
            <div class="form-group col-md-3">
              <%= f.text_field :last_name, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <h5>・社員氏名（フリガナ）</h5>
            <div class="form-group col-md-3">
              <%= f.text_field :first_name_kana, class: "form-control" %>
            </div>
            <div class="form-group col-md-3">
              <%= f.text_field :last_name_kana, class: "form-control" %>
            </div>
          </div>
          <div class="row d-flex flex-row">
            <h5>・生年月日</h5>
            <div class="form-group col-md-2 d-flex flex-row">
              <%= f.text_field :birth_year, class: "form-control mr-1" %><span>年</span>
            </div>
            <div class="form-group col-md-2 d-flex flex-row">
              <%= f.text_field :birth_month, class: "form-control" %><span>月</span>
            </div>
            <div class="form-group col-md-2 d-flex flex-row">
              <%= f.text_field :birth_day, class: "form-control" %><span>日</span>
            </div>
          </div>
          <div class="row">
            <h5>・電話番号</h5>
            <div class="form-group col-md-3" >
              <%= f.text_field :phone_number, class: "form-control" %>
            </diV>
          </div>
          <div class="row">
            <h5>・住所</h5>
            <div class="form-group col-md-4">
              <%= f.text_field :address, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <h5>・メールアドレス</h5>
            <div class="fomr-group col-md-3">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="form-group">
              <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/staff/members/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h1 class="mt-3 mb-4">所属社員一覧</h1>
      <div class="row">
        <div class="col-md-2">
          <%= render 'section_list', section: @sections %>
        </div>
        <div class="col-md-9">
          <div class="mb-4 text-center">
            <%= form_tag(members_path, method: :get) do %>
              <%= text_field_tag :search %>
              <%= submit_tag '検索', name: nil, class: "btn btn-success ml-2" %>
            <% end %>
          </div>
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>社員ID</th>
                <th>社員名</th>
                <th>所属課</th>
              </tr>
            </thead>
           <tbody>
              <% @member.each do |member| %>
              <tr>
                <td><%= member.id %></td>
                <td>
                  <%= link_to member_path(member.id) do %>
                    <%= member.first_name %><%= member.last_name %>
                  <% end %>
                </td>
                <td><%= member.section.section_name %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/staff/members/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1 class="mt-3 mb-4"><%= @member.first_name %><%= @member.last_name %>さんの詳細</h1>
        <div class="field d-flex flex-row">
          <h5 class="mr-4">・社員ID</h5>
          <b><%= @member.id %></b>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-4">・社員名</h5>
          <b><%= @member.first_name %>  <%= @member.last_name %></b>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-4">・社員名（フリガナ）</h5>
          <b><%= @member.first_name_kana %>  <%= @member.last_name_kana %></b>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-4">・所属課</h5>
          <b><%= @member.section.section_name %></b>
        </div>
        <div class="field d-flex flex-row">
          <h5 class="mr-4">・出勤状況</h4>
          <b><%= @member.attendance_status_i18n %></b>
        </div>
        <div class="row justify-content-end">
          <%= link_to "社員一覧画面へ", members_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/staff/members/top.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1 class="mt-3 mb-2">マイページ</h1>
      <div class="row justify-content-end">
        <%= link_to "登録情報を編集", edit_member_path(current_member.id), class: "btn btn-primary" %>
      </div>
      <div class="field d-flex flex-row">
        <h4 class="mr-5">・社員id</h4>
        <b><%= @member.id %></b>
      </div>
      <div class="field d-flex flex-row">
        <h4 class="mr-4">・社員名</h4>
        <b><%= @member.first_name %><%= @member.last_name %></b>
      </div>
      <div class="field d-flex flex-row">
        <h4 class="mr-4">・所属部門</h4>
        <b><%= @member.section.section_name %>
      </div>
      <div class="field d-flex flex-row">
        <h4 class="mr-5">・出退勤状況</h4>
        <%= form_with model: @member, url: change_path(current_member.id), method: :patch do |f| %>
          <%= f.radio_button :attendance_status, Member.attendance_statuses.key(0) %>
          <%= f.label :attendance_status,  Member.attendance_statuses_i18n[:leaving_work] %>

          <%= f.radio_button :attendance_status,  Member.attendance_statuses.key(1) %>
          <%= f.label :attendance_status, Member.attendance_statuses_i18n[:attendance] %>

          <%= f.submit "変更する", class: "btn btn-success ml-3" %>
        <% end %>
      </div>
      <div class="field mb-3">
        <h4 class="mb-5">・最近の体調</h4>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>登録日時</th>
              <th>体調</th>
              <th>体温</th>
              <th>補足説明</th>
            </tr>
          </thead>
          <tbody>
            <% @condition.each do |condition| %>
            <tr>
              <td><%= condition.created_at.to_s(:datetime_jp) %></td>
              <td><%= condition.status_i18n %></td>
              <td><%= condition.temperature %></td>
              <td><%= condition.explation %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="row justify-content-end">
        <%= link_to "体調状況を登録する", new_condition_path, class: "btn btn-primary mt-2" %>
      </div>
    </div>
  </div>
</div>