config/routes.rb
Rails.application.routes.draw do
  root to: 'staff/homes#start'

  namespace :admin do
    get 'graphs/:id' => "members#graph"
    get 'search' => 'search'
    resources :members, only: [:index, :show, :edit, :update]
  end
  scope module: :staff do
    get 'graphs' => 'conditions#graph'
    resources :conditions, only: [:new, :create, :show, :destroy, :index]
  end
  devise_for :members, skip: [:passwards], controllers: {
    registrations: "staff/registrations",
    sessions: 'staff/sessions',
  }

  devise_for :admins, skip: [:passwards, :registrations], controllers: {
    sessions: "admin/sessions",
  }

  scope module: :staff do
    get 'my_page' => 'members#top'
    patch 'change' => 'members#change'
    get "search" => "search"
    resources :members, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    get 'top' => 'homes#top'
  end

  namespace :admin do
    resources :sections, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :member

  enum status: { usually: 0, good: 1, bad: 2 }

  validates :temperature, { presence: true, numericality: true }
  validates :explation, length: { maximum: 50 }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
  has_many :condition

  def self.search(search)
    search ? where(["first_name like? OR last_name like?", "%#{search}%", "%#{search}"]) : all
  end

  enum attendance_status: { leaving_work: 0, attendance: 1 }

  validates :first_name, { presence: true }
  validates :last_name, { presence: true }
  validates :first_name_kana, { presence: true }
  validates :last_name_kana, { presence: true }
  validates :birth_year, { presence: true }
  validates :birth_month, { presence: true }
  validates :birth_day, { presence: true }
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :member

  validates :section_name, { presence: true, uniqueness: true }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @condition = Condition.order(created_at: :desc).limit(10)
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    type = params[:type] || Section.ids
    @member = Member.where(section_id: type).search(params[:search])
    @sections = Section.all
  end

  def show
    @member = Member.find(params[:id])
    @condition = @member.condition.limit(1).order(created_at: :desc)
  end

  def graph
    @member = Member.find(params[:id])
    @conditions = @member.condition
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to admin_member_path(@member.id)
  end

  private

  def member_params
    params.require(:member).permit(:section_id)
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @sections = Section.all
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to admin_sections_path
    else
      @sections = Section.all
      render :index
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to admin_sections_path
    else
      render :edit
    end
  end

  private

  def section_params
    params.require(:section).permit(:section_name)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:section_id, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_year, :birth_month, :birth_day, :phone_number, :address])
  end
end

app/controllers/staff/homes_controller.rb
class Staff::HomesController < ApplicationController
  def start
  end
end

app/controllers/staff/members_controller.rb
class Staff::MembersController < ApplicationController
  before_action :authenticate_member!

  def top
    @member = current_member
    @condition = @member.condition.limit(1).order(created_at: :desc)
  end

  def change
    @member = Member.find(current_member.id)
    @member.update(update_params)
    redirect_to my_page_path
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member = Member.find(current_member.id)
    if @member.update(member_params)
      redirect_to my_page_path
    else
      render :edit
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def index
    # if params[:type] == '1'
    #   @member = Member.where(section_id: 1)
    # elsif params[:type] == '2'
    #   @member = Member.where(section_id: 2)
    # else
    #   @member = Member.all.search(params[:search])
    # end
    type = params[:type] || Section.ids
    @member = Member.where(section_id: type).search(params[:search])
    @sections = Section.all
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :birth_year, :birth_month, :birth_day, :phone_number, :address, :email, :section_id, :attendance_status)
  end

  def update_params
    params.require(:member).permit(:attendance_status)
  end
end

app/controllers/staff/unlocks_controller.rb
# frozen_string_literal: true

class Staff::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staff/conditions_helper.rb
module Staff::ConditionsHelper
end

app/helpers/staff/homes_helper.rb
module Staff::HomesHelper
end

app/helpers/staff/members_helper.rb
module Staff::MembersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P_Con</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="vh-100">
    <header class="sticky-top">
      <div class=" bg-dark sgadow-sm">
        <nav class="navbar navbar-dark" >
          <div class="container d-flex justify-end" >
            <h1 class="text-white">
              P_Con
            </h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ui class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "TOPページへ",admin_top_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "社員一覧", admin_members_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "部門一覧", admin_sections_path, class: 'nav-item text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-item text-white' %>
                </li>
              <% elsif member_signed_in? %>
                <li class='nav-item'>
                  <%= link_to "マイページ", my_page_path, class: 'nav-item text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "体調登録履歴", conditions_path, class: 'nav-item text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "社員一覧", members_path, class: 'nav-item text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: 'nav-item text-white' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "TOPページ", root_path, class: 'nav-item text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_member_registration_path, class: 'nav-item text-white' %>
                </li>
                <li class="nav-item ">
                  <%= link_to "ログイン", new_member_session_path, class: 'nav-item text-white' %>
                </li>
              <% end %>
              </ui>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <main class="mb-6 main">
      <%= yield %>
    </main>
    <footer class="bg-dark pt-5 pb-6 w-100 fixed-bottom"></footer>
  </body>
</html>